### ISSUE TITLE
Module not eligible for use with Maker

### ISSUE THREAD

**Issue by valdivj** [IgnitionModuleDevelopmentCommunity/Kafka#5]
I compiled the module and installed in gateway.
It says "Module not eligible for use with Maker"
Am I out of luck on this one

**Comment by iatraviscox** [comment]
No, all you need to do is use the 8.0.14 SDK and override the following method to allow the module to work on Maker:

@Override
    public boolean isMakerEditionCompatible() {
        return true;
    }

You can create a PR if you want.

**Comment by valdivj** [comment]
Where does :
@override
public boolean isMakerEditionCompatible() {
return true;
}
have to be inserted

I tried putting it here:
/home/nx/Kafka/kafka-gateway/src/main/java/org/ignitionmdc/apache/kafka/GatewayHook.java

But when I compile it The compiler throws this error:
Compilation failure
[ERROR] /home/nx/Kafka/kafka-gateway/src/main/java/org/ignitionmdc/apache/kafka/GatewayHook.java:[36,5] method does not override or implement a method from a supertype

By the way thank you for youre help.

**Comment by Kevin-McClusky** [comment]
Make sure you update the module to use the 8.0.14 SDK (or later) like Travis mentioned.  After you do that, isMakerEditionCompatible() should be accessible.

You can change the Ignition SDK that's used in pom.xml.

**Comment by valdivj** [comment]
OK got it.
One quick question . Its in trail mode. Is that how it installs

**Comment by iatraviscox** [comment]
That is normal. The is not marked as free so it will appear to be in trial. However, there is no code that restricts the module when it is in trial. If you would like to remove that you can simply add the following override to the GatewayHook.java:

@Override
    public boolean isFreeModule() {
        return true;
    }

**Comment by Kevin-McClusky** [comment]
I just committed an update that makes the module both Maker Compatible and marked as Free.  (It was easy to do at the same time as some other updates.)  Enjoy!
